config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailout.urls", namespace="mailout")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailout/urls.py
from django.urls import path
from mailout.apps import MailoutConfig
from mailout.views import ClientsCreateView, ClientsUpdateView, MessageCreateView, ClientsListView, \
    MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, ClientsDeleteView, ClientsDetailView, \
    MailoutListView, MailoutCreateView, MailoutDetailView, MailoutUpdateView, MailoutDeleteView, AttemptListView, \
    AttemptCreateView, AttemptDetailView, AttemptUpdateView, AttemptDeleteView, HomeCreateView, HomeTemplateView, \
    StatisticsTemplateView

app_name = MailoutConfig.name

urlpatterns = [
    path('home/', HomeTemplateView.as_view(), name='home'),
    path('home/create/', HomeCreateView.as_view(), name='home_create'),

    path('clients/', ClientsListView.as_view(), name='clients'),
    path('client/create/', ClientsCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/detail/', ClientsDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientsDeleteView.as_view(), name='client_delete'),

    path('message/', MessageListView.as_view(), name='message'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailout/', MailoutListView.as_view(), name='mailout'),
    path('mailout/create/', MailoutCreateView.as_view(), name='mailout_create'),
    path('mailout/<int:pk>/detail/', MailoutDetailView.as_view(), name='mailout_detail'),
    path('mailout/<int:pk>/update/', MailoutUpdateView.as_view(), name='mailout_update'),
    path('mailout/<int:pk>/delete/', MailoutDeleteView.as_view(), name='mailout_delete'),

    path('attempt/', AttemptListView.as_view(), name='attempt'),
    path('attempt/create/', AttemptCreateView.as_view(), name='attempt_create'),
    path('attempt/<int:pk>/detail/', AttemptDetailView.as_view(), name='attempt_detail'),
    path('attempt/<int:pk>/update/', AttemptUpdateView.as_view(), name='attempt_update'),
    path('attempt/<int:pk>/delete/', AttemptDeleteView.as_view(), name='attempt_delete'),

    path('statistics/', StatisticsTemplateView.as_view(), name='statistics'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, UserDetailView, PasswordTemplateView, \
    UserListView, ManagerUpdateView, ManagerDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('create_user/', UserCreateView.as_view(), name='users_create'),
    path('list_users/', UserListView.as_view(), name='users_list'),
    path('update_user/<int:pk>/update/', UserUpdateView.as_view(), name='users_update'),
    path('detail_user/<int:pk>/detail/', UserDetailView.as_view(), name='users_detail'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path('change_password/', PasswordTemplateView.as_view(), name='password_change'),

    path('manager_update/<int:pk>/update/', ManagerUpdateView.as_view(), name='manager_update'),
    path('manager_detail/<int:pk>/detail/', ManagerDetailView.as_view(), name='manager_detail'),
]

mailout/forms.py
from django.forms import ModelForm, BooleanField
from mailout.models import Clients, Message, Mailout, Attempt


class ClientsForm(ModelForm):
    class Meta:
        model = Clients
        exclude = ('owner', )

    def __init__(self, *args, **kwargs):

        super(ClientsForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Укажите Email',
        })

        self.fields['full_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Укажите ФИО',
        })

        self.fields['notes'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Комментарий',
        })


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('created_at', 'owner')

    def __init__(self, *args, **kwargs):

        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields['subject'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Тема',
        })

        self.fields['message'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Сообщение',
        })


class MailoutForm(ModelForm):
    class Meta:
        model = Mailout
        fields = ('clients', 'message', 'status')

    def __init__(self, *args, **kwargs):

        super(MailoutForm, self).__init__(*args, **kwargs)

        self.fields['clients'].widget.attrs.update({
            'class': 'form-select',
            'multiple aria - label': "multiple select example",
            'placeholder': 'Получатели',
        })
        self.fields['clients'].label = 'Получатели рассылки'

        self.fields['message'].widget.attrs.update({
            'class': 'form-select',
            'placeholder': 'Сообщение',
        })
        self.fields['message'].label = 'Сообщение'

        self.fields['status'].widget.attrs.update({
            'class': 'form-select',
            'placeholder': 'Статус рассылки',
        })


class ManagerForm(ModelForm):
    class Meta:
        model = Mailout
        fields = ('status',)

    def __init__(self, *args, **kwargs):

        super(ManagerForm, self).__init__(*args, **kwargs)

        self.fields['status'].widget.attrs.update({
            'class': 'form-select',
            'placeholder': 'Статус рассылки',
        })


class AttemptForm(ModelForm):
    class Meta:
        model = Attempt
        fields = ('mailout',)

    def __init__(self, *args, **kwargs):

        super(AttemptForm, self).__init__(*args, **kwargs)

        self.fields['mailout'].widget.attrs.update({
            'class': 'form-select',
            'multiple aria - label': "multiple select example",
            'placeholder': 'Рассылка',
        })


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-label'
            field.widget.attrs['class'] = 'form-control'

mailout/views.py
import os
from datetime import datetime

from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from dotenv import load_dotenv
from django.core.mail import send_mail

from .forms import ClientsForm, MessageForm, MailoutForm, AttemptForm, ManagerForm
from .models import Home, Clients, Message, Mailout, Attempt
from .services import get_clients_from_cache

load_dotenv(override=True)


class HomeTemplateView(TemplateView):
    template_name = 'mailout/home.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        if user.is_authenticated:

            total_emails = int(Attempt.objects.filter(owner=user).count())
            mailing_success = int(Attempt.objects.filter(owner=user, status='Успешно').count())
            percent_success = round((mailing_success * 100) / total_emails)
            mailing_fail = Attempt.objects.filter(owner=user, status='Не успешно').count()
            percent_fail = round((mailing_fail * 100) / total_emails)

            data = {'mailing_active': Mailout.objects.filter(is_active=True).count(),
                    'mailing': Mailout.objects.all().count(),
                    'clients': Clients.objects.distinct('email').count(),
                    'total_emails': Mailout.objects.filter(owner=user).count(),
                    'mailing_success': Attempt.objects.filter(owner=user, status='Успешно').count(),
                    'mailing_fail': Attempt.objects.filter(owner=user, status='Не успешно').count(),
                    'percent_success': percent_success,
                    'percent_fail': percent_fail
                    }

            context.update(data)
            return context

        data = {'mailing_active': Mailout.objects.filter(is_active=True).count(),
                'mailing': Mailout.objects.all().count(),
                'clients': Clients.objects.distinct('email').count(),
                }

        context.update(data)
        return context


class HomeCreateView(CreateView):
    model = Home
    fields = ('total_users', 'total_mailout', 'total_active')
    template_name = 'mailout/home.html'
    success_url = reverse_lazy('mailout:home')


class ClientsCreateView(LoginRequiredMixin, CreateView):
    model = Clients
    form_class = ClientsForm
    template_name = 'mailout/clients_create.html'
    success_url = reverse_lazy('mailout:clients')

    def form_valid(self, form):
        clients = form.save()
        user = self.request.user
        clients.owner = user
        clients.save()
        return super().form_valid(form)


class ClientsListView(LoginRequiredMixin, ListView):
    model = Clients
    template_name = 'mailout/clients.html'
    context_object_name = 'clients'

    def get_queryset(self):
        queryset = get_clients_from_cache()
        return queryset

    def get_context_data(self, **kwargs):

        user = self.request.user
        context = super(ClientsListView, self).get_context_data(**kwargs)
        context['form'] = ClientsForm()

        if user.has_perm("product.can_view_client_info"):
            return context

        context['clients'] = Clients.objects.filter(owner=user)
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class ClientsDetailView(LoginRequiredMixin, DetailView):
    model = Clients
    template_name = 'mailout/client_view.html'
    context_object_name = 'client'


class ClientsUpdateView(LoginRequiredMixin, UpdateView):
    model = Clients
    form_class = ClientsForm
    template_name = 'mailout/clients.html'
    success_url = reverse_lazy('mailout:clients')


class ClientsDeleteView(LoginRequiredMixin, DeleteView):
    model = Clients
    success_url = reverse_lazy('mailout:clients')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailout/message_create.html'
    success_url = reverse_lazy('mailout:message')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'mailout/messages.html'
    context_object_name = 'messages'

    def get_context_data(self, **kwargs):

        user = self.request.user
        context = super(MessageListView, self).get_context_data(**kwargs)
        context['form'] = MessageForm()

        if user.has_perm("product.can_view_messages"):
            return context

        context['messages'] = Message.objects.filter(owner=user)
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'mailout/message_view.html'
    context_object_name = 'message'


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailout/messages.html'
    success_url = reverse_lazy('mailout:message')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailout:message')


class MailoutCreateView(LoginRequiredMixin, CreateView):
    model = Mailout
    form_class = MailoutForm
    template_name = 'mailout/mailout_create.html'
    success_url = reverse_lazy('mailout:mailout')

    def form_valid(self, form):
        mailout = form.save()
        user = self.request.user
        mailout.owner = user
        if mailout.status == 'Завершена':
            mailout.sent_at(auto_now_add=True)

        if mailout.status == 'Запущена':
            mailout.is_active = True

        mailout.save()

        return super().form_valid(form)


class MailoutListView(LoginRequiredMixin, ListView):
    model = Mailout
    form_class = MessageForm
    template_name = 'mailout/mailout.html'
    context_object_name = 'mailout'

    def get_context_data(self, **kwargs):

        user = self.request.user
        context = super(MailoutListView, self).get_context_data(**kwargs)
        context['form'] = MailoutForm()

        if user.has_perm("product.can_view_mailout"):
            return context

        context['mailout'] = Mailout.objects.filter(owner=user)
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class MailoutDetailView(LoginRequiredMixin, DetailView):
    model = Mailout
    template_name = 'mailout/mailout_view.html'
    context_object_name = 'mailout'


class MailoutUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailout
    form_class = MailoutForm
    template_name = 'mailout/mailout.html'
    success_url = reverse_lazy('mailout:mailout')

    def get_form_class(self):
        user = self.request.user

        if user == self.object.owner:
            return MailoutForm

        if user.has_perm("product.can_unpublish_products"):
            return ManagerForm

        raise PermissionDenied

    def form_valid(self, form):
        mailout = form.save()

        if mailout.status == 'Завершена':
            mailout.sent_at = datetime.now()

        if mailout.status == 'Запущена':
            mailout.is_active = True

        mailout.save()

        return super().form_valid(form)


class MailoutDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailout
    success_url = reverse_lazy('mailout:mailout')


class AttemptCreateView(LoginRequiredMixin, CreateView):
    model = Attempt
    form_class = AttemptForm
    template_name = 'mailout/attempt.html'
    success_url = reverse_lazy('mailout:attempt')

    def form_valid(self, form):

        clients = form.save()
        user = self.request.user
        clients.owner = user
        clients.save()

        attempt = form.save()

        try:

            send_mail(
                f"{attempt.mailout.message.subject}",
                f"{attempt.mailout.message.message}",
                os.getenv("EMAIL_HOST_USER"),
                [client.email for client in attempt.mailout.clients.all()],
                fail_silently=False,
            )

        except Exception as e:
            attempt.server_message = e
            attempt.status = 'Не успешно'

        else:
            attempt.server_message = 'Сообщение отправлено'
            attempt.status = 'Успешно'

        return super().form_valid(form)


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    form_class = AttemptForm
    template_name = 'mailout/attempt.html'
    context_object_name = 'attempts'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['form'] = AttemptForm()

        if user.is_authenticated:

            total_emails = int(Attempt.objects.filter(owner=user).count())
            mailing_success = int(Attempt.objects.filter(owner=user, status='Успешно').count())
            percent_success = round((mailing_success * 100) / total_emails)
            mailing_fail = Attempt.objects.filter(owner=user, status='Не успешно').count()
            percent_fail = round((mailing_fail * 100) / total_emails)

            data = {'total_emails': Attempt.objects.filter(owner=user).count(),
                    'mailing_success': Attempt.objects.filter(owner=user, status='Успешно').count(),
                    'mailing_fail': Attempt.objects.filter(owner=user, status='Не успешно').count(),
                    'percent_success': percent_success,
                    'percent_fail': percent_fail
                    }

            context.update(data)

mailout/templates/mailout/clients.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
    <p class="lead">Создайте свой список получателей рассылок</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% if object %}
                    <div class="card-header">
                        <h4 class="card-title pricing-card-title text-start">{{ clients.full_name }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>Email: {{ clients.email }}</li>
                            <li>Комментарий: {{ clients.notes }}</li>
                        </ul>
                    </div>
                    {% else %}
                    <h4 class="my-0 font-weight-normal">Список клиентов</h4>
                    {% if perms.clients.can_view_client_info %}
                    <table class="table table-striped">
                        <tr>
                            <td class="fw-semibold">Email получателя</td>
                            <td class="text-center fw-semibold">ФИО получателя</td>
                            <td class="text-center fw-semibold">Комментарий</td>
                            <td class="text-center fw-semibold">Пользователь</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        {% for client in clients %}
                        <tr>
                            <td class="w-25">{{ client.email }}</td>
                            <td>{{ client.full_name }}</td>
                            <td>{{ client.notes|truncatechars:100 }}</td>
                            <td>{{ client.owner }}</td>
                            <td><p><a class="link-primary" href="{% url 'mailout:client_detail' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                </svg>
                            </a></p></td>
                            {% if user == client.owner %}
                            <td><p><a class="link-primary" href="{% url 'mailout:client_update' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                </svg>
                            </a></p></td>
                            <td><p><a class="link-primary" href="{% url 'mailout:client_delete' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                  <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a></p></td>
                            {% else %}
                            <td></td>
                            <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                    {% else %}
                    <table class="table table-striped">
                        <tr>
                            <td class="fw-semibold">Email получателя</td>
                            <td class="text-center fw-semibold">ФИО получателя</td>
                            <td class="text-center fw-semibold">Комментарий</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        {% for client in clients %}
                        <tr>
                            <td class="w-25">{{ client.email }}</td>
                            <td>{{ client.full_name }}</td>
                            <td>{{ client.notes|truncatechars:100 }}</td>
                            <td><p><a class="link-primary" href="{% url 'mailout:client_detail' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                </svg>
                            </a></p></td>
                            <td><p><a class="link-primary" href="{% url 'mailout:client_update' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                </svg>
                            </a></p></td>
                            <td><p><a class="link-primary" href="{% url 'mailout:client_delete' client.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                  <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a></p></td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if object %}
                    <h4 class="my-0 font-weight-normal">Изменить данные получателя рассылки</h4>
                    {% else %}
                    <h4 class="my-0 font-weight-normal">Добавить нового получателя рассылки</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% if object %}
                    <form method="post" enctype="multipart/form-data" class="form-floating" action="{% url 'mailout:client_update' clients.pk %}">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="p-2 btn btn-outline-primary">Сохранить</button>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'mailout:clients' %}">Отмена</a>
                    </form>
                    {% else %}
                    <form method="post" enctype="multipart/form-data" class="form-floating" action="{% url 'mailout:client_create' %}">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="p-2 btn btn-outline-primary">Сохранить</button>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'mailout:clients' %}">Отмена</a>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}