config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailout.urls", namespace="mailout")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailout/urls.py
from django.urls import path
from mailout.apps import MailoutConfig
from mailout.views import ClientsCreateView, ClientsUpdateView, MessageCreateView, ClientsListView, \
    MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, ClientsDeleteView, ClientsDetailView, \
    MailoutListView, MailoutCreateView, MailoutDetailView, MailoutUpdateView, MailoutDeleteView, AttemptListView, \
    AttemptCreateView, AttemptDetailView, AttemptUpdateView, AttemptDeleteView, HomeCreateView, HomeTemplateView, \
    StatisticsTemplateView

app_name = MailoutConfig.name

urlpatterns = [
    path('home/', HomeTemplateView.as_view(), name='home'),
    path('home/create/', HomeCreateView.as_view(), name='home_create'),

    path('clients/', ClientsListView.as_view(), name='clients'),
    path('client/create/', ClientsCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/detail/', ClientsDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientsDeleteView.as_view(), name='client_delete'),

    path('message/', MessageListView.as_view(), name='message'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailout/', MailoutListView.as_view(), name='mailout'),
    path('mailout/create/', MailoutCreateView.as_view(), name='mailout_create'),
    path('mailout/<int:pk>/detail/', MailoutDetailView.as_view(), name='mailout_detail'),
    path('mailout/<int:pk>/update/', MailoutUpdateView.as_view(), name='mailout_update'),
    path('mailout/<int:pk>/delete/', MailoutDeleteView.as_view(), name='mailout_delete'),

    path('attempt/', AttemptListView.as_view(), name='attempt'),
    path('attempt/create/', AttemptCreateView.as_view(), name='attempt_create'),
    path('attempt/<int:pk>/detail/', AttemptDetailView.as_view(), name='attempt_detail'),
    path('attempt/<int:pk>/update/', AttemptUpdateView.as_view(), name='attempt_update'),
    path('attempt/<int:pk>/delete/', AttemptDeleteView.as_view(), name='attempt_delete'),

    path('statistics/', StatisticsTemplateView.as_view(), name='statistics'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, UserDetailView, PasswordTemplateView, \
    UserListView, ManagerUpdateView, ManagerDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('create_user/', UserCreateView.as_view(), name='users_create'),
    path('list_users/', UserListView.as_view(), name='users_list'),
    path('update_user/<int:pk>/update/', UserUpdateView.as_view(), name='users_update'),
    path('detail_user/<int:pk>/detail/', UserDetailView.as_view(), name='users_detail'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path('change_password/', PasswordTemplateView.as_view(), name='password_change'),

    path('manager_update/<int:pk>/update/', ManagerUpdateView.as_view(), name='manager_update'),
    path('manager_detail/<int:pk>/detail/', ManagerDetailView.as_view(), name='manager_detail'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=120, null=True, blank=True, verbose_name='Телефон')
    image = models.ImageField(upload_to='profile_img/', default='/profile_img/ava_001.png',
                              null=True, blank=True, verbose_name='Аватар')
    country = models.CharField(max_length=120, null=True, blank=True, verbose_name='Страна')

    STATUS_CHOICES = (('Менеджер', 'Менеджер'), ('Пользователь', 'Пользователь'))
    status = models.CharField(max_length=250, verbose_name='Статус', choices=STATUS_CHOICES, null=True, blank=True)

    is_blocked = models.BooleanField(default=False, verbose_name='Блокировка пользователя')

    token = models.CharField(max_length=100, verbose_name='Токен', null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ("managers", "Can view and block users"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BooleanField

from mailout.forms import StyleFormsMixin
from users.models import User


class UserRegisterForm(StyleFormsMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):

        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['password1'].widget.attrs.update({
            'placeholder': 'Придумайте пароль',
        })

        self.fields['password1'].label = 'Пароль'
        self.fields['password1'].help_text = ('Пароль должен состоять не менее, чем из 8 символов. '
                                              'Пароль не должен включать в себя легко вычисляемые сочетания символов.')

        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Повторите пароль',
        })

        self.fields['password2'].label = 'Подтверждение пароля'
        self.fields['password2'].help_text = ''

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите адрес электронной почты',
        })


class UserUpdateForm(StyleFormsMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('image', 'phone', 'country')
        exclude = ('password',)

    def __init__(self, *args, **kwargs):

        super(UserUpdateForm, self).__init__(*args, **kwargs)

        self.fields['image'].widget.attrs.update({
            'placeholder': '',
        })

        self.fields['image'].help_text = ''
        self.fields['image'].label = 'Your name'
        self.fields['image'].localized_field = 'Your name'
        self.fields['image'].fieldset = 'Your name'
        self.fields['image'].initial = "Your name"

        self.fields['phone'].widget.attrs.update({
            'placeholder': 'Укажите телефон',
        })

        self.fields['country'].widget.attrs.update({
            'placeholder': 'Укажите страну',
        })

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def clean_image(self):

        image = self.cleaned_data.get('image')
        image_size = image.size
        image_name = image.name
        max_size = 5 * 1024 * 1024

        if image_size > max_size:
            raise ValidationError('Размер файла не должен превышать 5МБ')

        elif not (image_name.endswith('png') or image_name.endswith('jpg')):
            raise ValidationError('Формат файла должен быть PNG или JPEG')

        return image


class ManagerForm(StyleFormsMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('image', 'phone', 'country', 'is_blocked',)
        exclude = ('password', 'image', 'phone', 'country')

    def __init__(self, *args, **kwargs):

        super(ManagerForm, self).__init__(*args, **kwargs)

        self.fields['is_blocked'].widget.attrs.update({
            'class': 'form-label',
            'placeholder': 'Заблокировать/разблокировать',
        })


class PasswordUpdateForm(StyleFormsMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):

        super(PasswordUpdateForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите адрес электронной почты',
        })


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-label'
            field.widget.attrs['class'] = 'form-control'

users/views.py
import secrets
import os
import random

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView, TemplateView, ListView
from dotenv import load_dotenv

from users.forms import UserRegisterForm, UserUpdateForm, PasswordUpdateForm, ManagerForm
from users.models import User

load_dotenv(override=True)


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:login')
    context_object_name = 'users'

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(5)
        user.token = token
        user.save()
        url = f'http://{self.request.get_host()}/users/email_confirm/{token}/'

        send_mail(
            "Подтверждение адреса электронной почты",
            f"Подтвердите регистацию на сайте Mailout. Перейдите по ссылке: {url} .",
            os.getenv("EMAIL_HOST_USER"),
            [f"{user.email}"],
            fail_silently=False,
        )

        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_update_form.html'
    success_url = reverse_lazy('mailout:home')


class UserListView(ListView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/users_list.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):

        user = self.request.user
        context = super(UserListView, self).get_context_data(**kwargs)

        if user.has_perm("managers"):
            context["status"] = "Менеджер"
            return context

        context["status"] = "Пользователь"
        return context


class UserDetailView(DetailView):
    model = User
    template_name = 'users/personal_account.html'
    context_object_name = 'user'


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class PasswordTemplateView(TemplateView):

    form_class = PasswordUpdateForm
    template_name = 'users/password_form.html'
    success_url = reverse_lazy('users:login')

    def post(self, request):

        if request.method == 'POST':
            email = request.POST.get('email')
            user = User.objects.filter(email=email).first()
            if user:

                password = str(random.randint(10000000, 99999999))
                user.set_password(password)
                user.save()

                send_mail(
                    "Смена пароля",
                    f"Ваш новый пароль: {password} .",
                    os.getenv("EMAIL_HOST_USER"),
                    [f"{email}"],
                    fail_silently=False,
                )

        return render(request, 'login.html')

    def get_context_data(self, **kwargs):

        context = super(PasswordTemplateView, self).get_context_data(**kwargs)
        context['form'] = PasswordUpdateForm()

        return context


class ManagerUpdateView(UpdateView):
    model = User
    form_class = ManagerForm
    template_name = 'users/user_update_form.html'
    success_url = reverse_lazy('mailout:home')


class ManagerDetailView(DetailView):
    model = User
    template_name = 'users/manager_view.html'
    context_object_name = 'user'

users/templates/users/manager_view.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
    <p class="lead">Mailout - это сервис по управлению Вашими рассылками</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="card-title pricing-card-title text-start">{{ user.email }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{% if user.image.url %} <img src="{{ user.image.url }}"> {% else %} <img src="/media/profile_img/ava_001.png"> {% endif %} </li>
                        <li>Телефон: {% if user.phone %} {{ user.phone }} {% else %} не указан {% endif %}</li>
                        <li>Страна: {% if user.country %} {{ user.country }} {% else %} не указана {% endif %}</li>
                    </ul>
                </div>
            </div>
        </div>
        <a class="icon-link" href="{% url 'users:manager_update' user.pk %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
          </svg>
          Заблокировать/Разблокировать
        </a>
    </div>

{% endblock %}

users/templates/users/password_form.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Восстановить пароль</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" class="form-floating" action="{% url 'users:password_change' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary mt-3">
                            Восстановить
                        </button>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary mt-3" href="{% url 'users:login'%}" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/personal_account.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
    <p class="lead">Mailout - это сервис по управлению Вашими рассылками</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="card-title pricing-card-title text-start">{{ user.email }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{% if user.image.url %} <img src="{{ user.image.url }}"> {% else %} <img src="/media/profile_img/ava_001.png"> {% endif %} </li>
                        <li>Телефон: {% if user.phone %} {{ user.phone }} {% else %} не указан {% endif %}</li>
                        <li>Страна: {% if user.country %} {{ user.country }} {% else %} не указана {% endif %}</li>
                    </ul>
                </div>
            </div>
        </div>
        <a class="icon-link" href="{% url 'users:users_update' user.pk %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
          </svg>
          Редактировать профиль
        </a>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Зарегистрироваться</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary mt-3">
                            Зарегистрироваться
                        </button>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary mt-3" href="{% url 'mailout:home'%}" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_update_form.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Изменить данные</h4>
                </div>
                <h4 class="my-0 font-weight-normal mx-3 mt-2">{{ user.email }}</h4>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary mt-3">
                            Сохранить
                        </button>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary mt-3" href="{% url 'mailout:home'%}" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/users_list.html
{% extends 'mailout/base.html' %}

{% block title %}Mailout{% endblock %}

{% block content %}

{% include 'mailout/header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailout</h1>
    <p class="lead">Пользователи</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">

                    <h4 class="my-0 font-weight-normal">Список пользователей</h4>
                    <table class="table table-striped">
                        <tr>
                            <td class="fw-semibold">Email</td>
                            <td class="fw-semibold">Статус</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        {% for user in users %}
                        <tr>
                            <td class="w-25">{{ user.email }}</td>
                            <td>{{ user.status }}</td>

                            <td><p><a class="link-primary" href="{% url 'users:manager_detail' user.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                </svg>
                            </a></p></td>
                            <td><p><a class="link-primary" href="{% url 'users:manager_update' user.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-slash" viewBox="0 0 16 16">
                                  <path d="M13.879 10.414a2.501 2.501 0 0 0-3.465 3.465zm.707.707-3.465 3.465a2.501 2.501 0 0 0 3.465-3.465m-4.56-1.096a3.5 3.5 0 1 1 4.949 4.95 3.5 3.5 0 0 1-4.95-4.95ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-9 8c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
                                </svg>
                            </a></p></td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>
        </div>
    </div>

{% endblock %}